### ISSUE TITLE
Cannot checkout `main` after cloning

### ISSUE THREAD

**Issue by carsakiller** [LuaLS/vscode-lua#95]
I don't currently have another macOS-level account set up (and running VSCode with a separate profile directory doesn't seem to give it a separate set of installed extensions), but I just did some more testing: deleted `addonManager`, launched VSCode (without any version of the Lua extension installed), and installed build \#262 from the .vsix… and it got an error again. But it looks a little different this time:

```
#### STARTUP ####
[2023-03-04 02:04:17] |   DEBUG   |     Filesystem     | Created directory at "/Users/██████/Library/Application Support/Code/User/globalStorage/sumneko.lua/addonManager"
[2023-03-04 02:04:17] |   ERROR   |         Git        | Failed to pull LLS-Addons!
[2023-03-04 02:04:17] |   ERROR   |         Git        | error: pathspec 'main' did not match any file(s) known to git
```

That's the first time I've seen the last line from Git be something other than `fatal: not a git repository (or any of the parent directories): .git`. I'm not entirely sure which directory it's trying to do a `git pull` in. I can't find anything called `LLS-Addons`, and the only `.git` directory I see anywhere inside `globalStorage/sumneko.lua` is directly inside `addonManager`.

_Originally posted by @Rhys-T in https://github.com/LuaLS/vscode-lua/issues/81#issuecomment-1454599642_

**Comment by carsakiller** [comment]
I have added some commits that should fix this error. @Rhys-T can you please try the vsix from [action #263](https://github.com/LuaLS/vscode-lua/actions/runs/4331153585) 🙂

**Comment by Rhys-T** [comment]
Just installed that one, no errors even after relaunching VSCode… but I still had the `addonManager` directory from before. I don't know whether it pulled successfully, or just didn't attempt it for some reason. Anything particular you need me to check for? Do I need to try again with that folder deleted, to make sure starting from scratch works too?

**Comment by carsakiller** [comment]
Try deleting the `addonManager` directory and reloading VS Code. It should say in the log if everything has gone well. Thanks for the help!

**Comment by Rhys-T** [comment]
Okay, I quit VSCode, deleted `addonManager`, and relaunched… only to discover that the Lua extension had mysteriously uninstalled itself [again](https://github.com/LuaLS/vscode-lua/issues/81#issuecomment-1454314392).

I reinstalled from the \#263 .vsix, and three messages popped up in the corner:

> ⊗ Server initialization failed.
> Source: Lua (Extension)

> ⊗ Pending response rejected since connection got disposed

> ⓘ Completed installing Lua extension from VSIX.

<details>
<summary>Screenshot</summary>

<img width="498" alt="Screen Shot 2023-03-04 at 5 57 09 PM" src="https://user-images.githubusercontent.com/108157737/222932560-b2f5421e-d8be-417c-a3ff-98f3eb726d54.png">

</details>

When I clicked "Go to output" on the first one, I got this:

```
/Users/██████/.vscode/extensions/sumneko.lua-3.6.16/server/bin/lua-language-server: create_directories: File exists: "/Users/██████/.vscode/extensions/sumneko.lua-3.6.16/server/log/cache/3023"
stack traceback:
	[C]: in function 'bee.filesystem.create_directories'
	script/service/service.lua:254: in function 'service.lockCache'
	script/service/service.lua:273: in function 'service.start'
	...██/.vscode/extensions/sumneko.lua-3.6.16/server/main.lua:79: in main chunk
	...vscode/extensions/sumneko.lua-3.6.16/server/bin/main.lua:85: in main chunk
	[C]: in ?
[Info  - 5:57:04 PM] Connection to server got closed. Server will restart.
[Error - 5:57:04 PM] Server initialization failed.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
[Error - 5:57:04 PM] Lua client: couldn't create connection to server.
  Message: Pending response rejected since connection got disposed
  Code: -32097 
Log path: file:///Users/██████/.vscode/extensions/sumneko.lua-3.6.16/server/log/file_Users_██████_.hammerspoon.log
```

---

Also (because I'm not very familiar with VSCode extension development), is there an easy way to get to the log files I was sending before, when VSCode _isn't_ displaying an error notification? Previously, I was clicking the 'report' button, which opened the log in Console.app, but also brought up the GitHub 'create issue' page, which I then had to close (since I was responding to an existing issue).

**Comment by carsakiller** [comment]
That error doesn't seem to have anything to do with the addon manager—it appears to just be related to the language server. If it persists, it may be worth *yet another issue*, but for the [language server](https://github.com/LuaLS/lua-language-server).

The logs can be found by clicking the log icon in the addon manager, if it is working.
![image](https://user-images.githubusercontent.com/61925890/222932862-7814fa4d-de03-4a17-b0e0-3d22a76789fa.png)

Alternatively, you can open the `Output` menu and select `Lua Addon Manager` from the dropdown.

You should be able to start VS Code, run the open addon manager command, and enable an addon, with no errors.

**Comment by Rhys-T** [comment]
> That error doesn't seem to have anything to do with the addon manager—it appears to just be related to the language server. If it persists, it may be worth _yet another issue_, but for the [language server](https://github.com/LuaLS/lua-language-server).

Gotcha. I'll keep an eye out for it, and report it in that repo if it seems to keep happening.

> The logs can be found by clicking the log icon in the addon manager, if it is working. [screenshot]
> 
> Alternatively, you can open the `Output` menu and select `Lua Addon Manager` from the dropdown.
> 
> You should be able to start VS Code, run the open addon manager command, and enable an addon, with no errors.

Ah - I hadn't actually seen the addon manager before, just the errors. (Haven't really explored the full functionality of this extension yet.) Just relaunched VSCode… and the Lua extension uninstalled itself _again_, even though I'm certain it was still showing installed just before I quit! Reinstalled again, didn't see the language server errors this time, and relaunched… it disappeared again. Am I doing something wrong? I don't see anything indicating that installing from a .vsix will make it 'temporary' or anything…

(Just to be clear, I've only had this problem with the .vsix builds from GitHub. It stayed installed just fine when I was using the version from the Marketplace.)

**Comment by carsakiller** [comment]
I believe that is just how the VSIX install works, it is meant for temporary testing and will not persist between restarts-that is to be expected. The addon manager is working now with no errors? Running the `open addon manager` command works as well?

**Comment by Rhys-T** [comment]
Reinstalled to check, and got the language server error again - I'll have to look into that. The addon manager works fine as far as I can tell - successfully installed the LuaFileSystem addon.

Then Lua suddenly jumped to the top of the extensions sidebar, showing a "Reload Required" button - because it had uninstalled itself again, and needed to reload the window to finish removing it! Reloaded, reinstalled, and the LuaFileSystem addon was still there.

No idea why the extension keeps disappearing. I've installed (my own custom) extensions from .vsix before, and never had them do this. I can't find any reference to .vsix files working that way for anyone else. And I can't yet find any pattern as to _when_ it decides to go away.

**Comment by carsakiller** [comment]
I'm not sure what would be causing the extension to uninstall itself… maybe settings sync? I think I remember having the same thing happen to me before, though—I just thought it was intentional 😄. Glad the addon manager is working now, I'll close this issue.
